FROM haproxy:1.6

RUN apt-get update && \
    apt-get install -y socat && \
    apt-get install -y iputils-ping && \
    apt-get install -y dnsutils && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 80

ADD stick-table.sh .
ADD run-dev.sh .
ADD haproxy.cfg-dev.sh .

CMD ["./run-dev.sh"]
